
name: Performance Testing
on: 
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain (without https)'     
        required: true
        default: 'beta.newdimensionsactive.ie'
      vus:
        required: true
        default: 300
        description: 'Number of virtual users'  
      minTime:
        required: true
        default: '1m'
        description: 'Min Time'  
      maxTime:
        required: true
        default: '30m'
        description: 'Max Time'  

# on:
#   schedule:
#     - cron: '*/15 * * * *' ## IN CASE OF A SCHEDULED TEST

jobs:
  k6_local_perf_soak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run local k6 test
        uses: k6io/action@v0.1
        with:
          filename: k6-nda-SoakTest.js
          flags: -e TARGET_VUS=${{ github.event.inputs.vus }} -e TARGET_DOMAIN=${{ github.event.inputs.domain }} -e MIN_TIME=${{ github.event.inputs.minTime }} -e MAX_TIME=${{ github.event.inputs.maxTime }}
  google_insights:
    runs-on: ubuntu-latest
    steps:
      - name: Running Page Speed Insights Mobile
        uses: jakepartusch/psi-action@v1.1
        id: psim
        with:
          url: "https://${{ github.event.inputs.domain }}/"
          threshold: 30
          strategy: mobile
      - name: Running Page Speed Insights Desktop
        uses: jakepartusch/psi-action@v1.1
        id: psid
        with:
          url: "https://${{ github.event.inputs.domain }}/"
          threshold: 70
          strategy: desktop
